# Generated by Django 5.0.1 on 2025-06-18 13:00

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=upload.models.get_upload_path),
        ),
    ]
